FROM alpine:3.8

LABEL maintainer="kwf2030 <kwf2030@163.com>" \
      version="master"

RUN echo "http://mirrors.aliyun.com/alpine/v3.8/main" > /etc/apk/repositories && \
    echo "http://mirrors.aliyun.com/alpine/v3.8/community" >> /etc/apk/repositories

RUN apk update && \
    apk upgrade && \
    apk add --no-cache git && \
    apk add --virtual build-base && \
    mkdir -p /beanstalk/bin /beanstalk/data

WORKDIR /beanstalk

RUN git clone https://github.com/beanstalkd/beanstalkd.git src

WORKDIR /beanstalk/src

RUN make && \
    cp beanstalkd ../bin/ && \
    make clean

WORKDIR /beanstalk/bin

ENV BEANSTALK_PORT=11300

ENTRYPOINT ./beanstalkd -b /beanstalk/data -f 60000 -l 0.0.0.0 -p $BEANSTALK_PORT -z 16777216
